layout_spectrum: 0.8897243
typography_spectrum: 0.381579
color:
  lightness: 0.609936
  brandStrength: 0.4460306
  saturation: 0.4182069
  rhythmicContrast: 0.7172968
  brandColors:
    - '#0590CF'
    - '#030610'
    - '#999BCF'
    - '#434B4C'
    - '#CF806E'
name: Focal Point Ministries
